# Generated by Django 6.1.1 on 2026-09-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_alter_question_options_remove_question_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='available_days',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='available_times',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_level',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_lesson_duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='quran_memorization',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض'), ('suspended', 'موقوف')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='study_stage',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='available_days',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='available_times',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='ijazah',
            field=models.FileField(blank=True, null=True, upload_to='teachers/ijazah/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='quran_memorization',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='recitation_audio',
            field=models.FileField(blank=True, null=True, upload_to='teachers/recitations/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='specializations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض'), ('suspended', 'موقوف')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='tajweed_level',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teaching_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
