# Generated by Django 6.1.1 on 2026-09-15 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_studentprofile_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academy.teacherprofile'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور'), ('open', 'مفتوح'), ('مغلق', 'Closed'), ('archived', 'مؤرشف')], default='draft', max_length=20),
        ),
    ]
